### ISSUE TITLE
will a tex version of a thesis accept by the school?

### ISSUE THREAD

**Issue by zhongjingjogy** [alittlealone/csuthesisTemplate#1]
Hi,

I'm a graduate of CSU, too. And I really wonder if a tex version of thesis is accepted by the school, or not. I ask some seniors who are writing theirs thesis and I could not get any answer.

Best wishes!

**Comment by von1000** [comment]
Actually, I don't know, either.....You can ask your mentor.
And I just found out that equations can be written in TeX using MathType, which makes Word really easy to use. So I'm planning on using Word rather than LaTeX...

**Comment by zhongjingjogy** [comment]
Unfortunately, Word would be the best optional for CSU.
